In [ ]:
import tensorflow as tf

In [2]:
a = tf.constant([1.0, 2.0], name = "a")
b = tf.constant([2.0, 3.0], name = "b")
result = a + b

sess = tf.Session()
sess.run(result)

array([3., 5.], dtype=float32)

In [3]:
print(a.graph is tf.get_default_graph())

True


In [4]:
g1 = tf.Graph()
with g1.as_default():
    v = tf.get_variable("v", shape=[1], initializer=tf.zeros_initializer)

g2 = tf.Graph()
with g2.as_default():
    v = tf.get_variable("v", shape=[1], initializer=tf.ones_initializer)
    
with tf.Session(graph=g1) as sess:
    tf.global_variables_initializer().run()
    with tf.variable_scope("", reuse=True):
        print(sess.run(tf.get_variable("v")))
        
with tf.Session(graph=g2) as sess:
    tf.global_variables_initializer().run()
    with tf.variable_scope("", reuse=True):
        print(sess.run(tf.get_variable("v")))

[0.]
[1.]


In [5]:
#http://playground.tensorflow.org/

In [6]:
w1 = tf.Variable(tf.random_normal((2,3), stddev=1, seed=1))
w2 = tf.Variable(tf.random_normal((3,1), stddev=1, seed=1))

x = tf.constant([[0.7, 0.9]])

a = tf.matmul(x, w1)
y = tf.matmul(a, w2)

sess = tf.Session()
sess.run(w1.initializer)
sess.run(w2.initializer)
print(sess.run(w1))
print(sess.run(a))
print(sess.run(w2))
print(sess.run(y))
sess.close()

[[-0.8113182   1.4845988   0.06532937]
 [-2.4427042   0.0992484   0.5912243 ]]
[[-2.7663565  1.1285427  0.5778324]]
[[-0.8113182 ]
 [ 1.4845988 ]
 [ 0.06532937]]
[[3.957578]]
